import { BoardCell } from '../types';

// ============================================================
// BOARD DATA - 40 Petak MonopoliWNI
// ============================================================

export const BOARD_CELLS: BoardCell[] = [
  // === SISI 1: KAMPUNG/KOSAN (0-9) ===
  {
    index: 0,
    name: 'Tanggal Muda',
    type: 'corner',
    group: null,
    price: null,
    rent: null,
    description: 'Start/Go - Dapat Rp200rb saat lewat',
    color: '#22c55e',
  },
  {
    index: 1,
    name: 'Kontrakan Petak',
    type: 'property',
    group: 'coklat',
    price: 100000,
    rent: 20000,
    description: 'Kontrakan murah meriah',
    color: '#92400e',
  },
  {
    index: 2,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 3,
    name: 'Warkop Sebelah Kosan',
    type: 'property',
    group: 'coklat',
    price: 120000,
    rent: 25000,
    description: 'Warkop favorit anak kos',
    color: '#92400e',
  },
  {
    index: 4,
    name: 'Pajak Pendapatan',
    type: 'tax',
    group: null,
    price: null,
    rent: null,
    description: 'Bayar 10% saldo',
    color: '#6b7280',
  },
  {
    index: 5,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 6,
    name: 'Angkringan',
    type: 'property',
    group: 'cyan',
    price: 140000,
    rent: 28000,
    description: 'Angkringan legendaris',
    color: '#06b6d4',
  },
  {
    index: 7,
    name: 'Kantor Polisi',
    type: 'corner',
    group: null,
    price: null,
    rent: null,
    description: 'Skip 1 giliran',
    color: '#1e40af',
  },
  {
    index: 8,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 9,
    name: 'Warnet Jadul',
    type: 'property',
    group: 'cyan',
    price: 160000,
    rent: 32000,
    description: 'Warnet jadul bandwidth kenceng',
    color: '#06b6d4',
  },

  // === SISI 2: PERKOTAAN (10-19) ===
  {
    index: 10,
    name: 'THR Bonus',
    type: 'corner',
    group: null,
    price: null,
    rent: null,
    description: 'Ambil dari pot',
    color: '#eab308',
  },
  {
    index: 11,
    name: 'Kontrakan 3 Pintu',
    type: 'property',
    group: 'pink',
    price: 200000,
    rent: 40000,
    description: 'Kontrakan premium',
    color: '#ec4899',
  },
  {
    index: 12,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 13,
    name: 'Franchise Es Teh',
    type: 'property',
    group: 'pink',
    price: 220000,
    rent: 45000,
    description: 'Es teh viral everywhere',
    color: '#ec4899',
  },
  {
    index: 14,
    name: 'Minimarket 24 Jam',
    type: 'property',
    group: 'pink',
    price: 250000,
    rent: 50000,
    description: 'Indomaret/Sayur terserah',
    color: '#ec4899',
  },
  {
    index: 15,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 16,
    name: 'Pajak PPN',
    type: 'tax',
    group: null,
    price: null,
    rent: null,
    description: 'Bayar 15% saldo',
    color: '#6b7280',
  },
  {
    index: 17,
    name: 'Lampu Merah 300 Detik',
    type: 'property',
    group: 'orange',
    price: 230000,
    rent: 46000,
    description: 'Lampu merah terpanjang',
    color: '#f97316',
  },
  {
    index: 18,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 19,
    name: 'Rumah Kos Eksklusif',
    type: 'property',
    group: 'orange',
    price: 280000,
    rent: 55000,
    description: 'Kos AC + WiFi + Cleaning',
    color: '#f97316',
  },

  // === SISI 3: ZONA GENGSI (20-29) ===
  {
    index: 20,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir (Center)',
    color: '#3b82f6',
  },
  {
    index: 21,
    name: 'Apartemen Sultan',
    type: 'property',
    group: 'merah',
    price: 500000,
    rent: 100000,
    description: 'Apartemen buat sultan',
    color: '#ef4444',
  },
  {
    index: 22,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 23,
    name: 'Coworking Space Aesthetic',
    type: 'property',
    group: 'merah',
    price: 450000,
    rent: 90000,
    description: 'Workation vibes',
    color: '#ef4444',
  },
  {
    index: 24,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 25,
    name: 'Mall Mewah',
    type: 'property',
    group: 'kuning',
    price: 600000,
    rent: 120000,
    description: 'Mall paling mewah',
    color: '#eab308',
  },
  {
    index: 26,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 27,
    name: 'Restoran Viral TikTok',
    type: 'property',
    group: 'kuning',
    price: 550000,
    rent: 110000,
    description: 'Restoran viral 100k views',
    color: '#eab308',
  },
  {
    index: 28,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 29,
    name: 'Barbershop Kekinian',
    type: 'property',
    group: 'kuning',
    price: 400000,
    rent: 80000,
    description: 'Barbershop aesthetic',
    color: '#eab308',
  },

  // === SISI 4: ZONA ABU-ABU (30-39) ===
  {
    index: 30,
    name: 'THR Bonus',
    type: 'corner',
    group: null,
    price: null,
    rent: null,
    description: 'Ambil dari pot',
    color: '#eab308',
  },
  {
    index: 31,
    name: 'Pinjol Legal',
    type: 'property',
    group: 'hijau',
    price: 300000,
    rent: 60000,
    description: 'Pinjol resmi OJK',
    color: '#22c55e',
  },
  {
    index: 32,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 33,
    name: 'Pinjol Ilegal',
    type: 'event',
    group: null,
    price: null,
    rent: null,
    description: 'Bayar 20% atau skip 2 giliran',
    color: '#dc2626',
  },
  {
    index: 34,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 35,
    name: 'Kripto Corner',
    type: 'property',
    group: 'hijau',
    price: 350000,
    rent: 70000,
    description: 'To the moon or to zero',
    color: '#22c55e',
  },
  {
    index: 36,
    name: 'Kegiatan Seru',
    type: 'draw_kegiatan',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Kegiatan',
    color: '#f59e0b',
  },
  {
    index: 37,
    name: 'Investasi Bodong Corner',
    type: 'event',
    group: null,
    price: null,
    rent: null,
    description: 'Efek acak besar',
    color: '#dc2626',
  },
  {
    index: 38,
    name: 'Takdir Netizen',
    type: 'draw_takdir',
    group: null,
    price: null,
    rent: null,
    description: 'Narik kartu Takdir',
    color: '#3b82f6',
  },
  {
    index: 39,
    name: 'Tax Audit',
    type: 'tax',
    group: null,
    price: null,
    rent: null,
    description: 'Bayar 25% saldo',
    color: '#6b7280',
  },
];

// Helper functions
export function getCellByIndex(index: number): BoardCell {
  return BOARD_CELLS[index % 40];
}

export function getPropertyCells(): BoardCell[] {
  return BOARD_CELLS.filter(cell => cell.type === 'property');
}

export function getDrawTakdirCells(): BoardCell[] {
  return BOARD_CELLS.filter(cell => cell.type === 'draw_takdir');
}

export function getDrawKegiatanCells(): BoardCell[] {
  return BOARD_CELLS.filter(cell => cell.type === 'draw_kegiatan');
}

export function getGroupCells(group: string): BoardCell[] {
  return BOARD_CELLS.filter(cell => cell.group === group);
}

export function calculateRent(baseRent: number, houseLevel: number, groupOwned: boolean): number {
  let rent = baseRent;
  if (houseLevel > 0) {
    rent = baseRent * (1 + houseLevel * 0.5);
  }
  if (groupOwned) {
    rent *= 2;
  }
  return Math.floor(rent);
}
